In [2]:
lst=[]
for i in range(2000,3201):    
    if i%7==0 and i%5!=0:
        lst.append(i)
print(lst)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [5]:
x=int(input("val :"))
res=1
for i in range(1,x+1):
    res*=i
print("factorial",x,"is",res)

val :20
factorial 20 is 2432902008176640000


In [7]:
x=int(input("val :"))
dict1={}
for i in range(1,x+1):
    dict1[i]=i**2
print(dict1)

val :8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [9]:
x=input("string :")
i=int(input("index :"))
x=x.replace(x[i],"")
print(x)

string :Example
index :2
Exmple


In [2]:
import numpy as np
arr=np.array(input("Array :"))
print("Original array elements:",arr)
print("Array to list:",arr.tolist())

Array :[[0,1],[2,3],[4,5]]
Original array elements: [[0,1],[2,3],[4,5]]
Array to list: [[0,1],[2,3],[4,5]]


In [10]:
 import numpy as np 
x = [0,1,2] 
y = [2,1,0] 
z=np.array([x,y])
print(np.cov(z))

[[ 1. -1.]
 [-1.  1.]]


In [19]:
import math
D=input("D values:")
x=D.split(",")
p=0
for i in x:
    p+=1
    r=int(math.sqrt((2*50*(int(i)))/30))
    print("Q",p,"=",r)

D values:100,150,180
Q 1 = 18
Q 2 = 22
Q 3 = 24


In [46]:
import numpy
a=np.array([[0,1],[1,2], [3,4]])
b=np.array([[5, 6,8], [7, 8,7]])
c=np.zeros([a.shape[0]+b.shape[0],a.shape[1]+b.shape[1]])
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
           c[i][j]=a[i][j]
for i in range(a.shape[0],c.shape[0]):
    for j in range(a.shape[1],c.shape[1]):
        c[i][j]=b[i-a.shape[0]][j-a.shape[1]]
print(c)

[[0. 1. 0. 0. 0.]
 [1. 2. 0. 0. 0.]
 [3. 4. 0. 0. 0.]
 [0. 0. 5. 6. 8.]
 [0. 0. 7. 8. 7.]]
